api_version = "2025-07"

[[extensions]]

uid = "f86d6b7d-d4cf-b24d-e702-9ea1af534ed4c5ff8950"

type = "ui_extension"
name = "Swipe Contact After Render"
handle = "swipe-contact-after-render"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/index.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
network_access = true
api_access = true

# type = "checkout_ui_extension"
# name = "Swipe Contact After Render"
# extension_points = [
#   'Checkout::Contact::RenderAfter'
# ]

# [capabilities]
# network_access = true
# api_access = true

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key-2"

# Read more on extension settings at https://shopify.dev/api/checkout-extensions/checkout/configuration
# [settings]
#   [[settings.fields]]
#   key = "banner_title"
#   type = "single_line_text_field"
#   name = "Banner title"
#   description = "Enter a title for the banner"
