api_version = "2025-07"

[[extensions]]
uid = "0278bbe2-8504-6785-98ae-46a8045bf875a5b2fca6"
type = "ui_extension"
name = "Swipe Dynamic Render"
handle = "swipe-dynamic-render"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/index.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
network_access = true
api_access = true

# type = "checkout_ui_extension"
# name = "Swipe Dynamic Render"
# 
# extension_points = [
#   'Checkout::Dynamic::Render'
# ]

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key-2"

# Read more on extension settings at https://shopify.dev/api/checkout-extensions/checkout/configuration
# [settings]
#   [[settings.fields]]
#   key = "banner_title"
#   type = "single_line_text_field"
#   name = "Banner title"
#   description = "Enter a title for the banner"
