api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "checkout-validation-rule"
type = "function"
uid = "28230270-5c28-8795-f4c2-4e5ba875b03903d8d108"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
